### ISSUE TITLE
dudas cómo instalar ?

### ISSUE THREAD

**Issue by moebiussurfing** [necsoft/codepoems#81]
Hola buenas, no sabía si escribirte en privado, pero igual le sirva a alguien más estando aquí.
No conseguí instalar nw-builder... Lo cloné con la app de github y lo mismo con codepoems.

No me encuentra el comando (ni lo veo en las subcarpetas): 

npm install nw-builder --save-dev

Si me dieras alguna pista estaría genial, pues tengo curiosidad por probarlo. gracias!

**Comment by necsoft** [comment]
No hay problema, gracias por escribirme, tenía pensado mejorar la forma en la que esta explicado pero básicamente lo que yo hago es lo siguiente. Tengo instalado [nw-builder](https://github.com/nwjs/nw-builder) y he creado dos scripts dentro del **package.json** para correr por npm. Actualmente solo esta funcionando para Mac OS X.

Entonces al correr `npm run build_osx64` se crea una carpeta build que dentro tiene el ejecutable. Si te tira algun error diferente manda algun screenshot o un log, ah y también sería util saber en que versión de node estas instalando globalmente nw-builder, porque quizas puede ser que no se termina de instalar bien porque no esta actualizado, si mal no recuerdo, nw-builder no funcionaba con una versión de 0.11.*

**Comment by moebiussurfing** [comment]
gracias por la respuesta! Ignorantemente, ni sabía que había que instalar node.js, perdón.
Instalé la última (v4 OSX) y ya pude instalaer nw-builder creo:
Local: npm install nw-builder --save-dev
No sé si hay que hacer algo más..

Luego de clonar el repositorio de codepoems, dentro de a carpeta, hago:
npm install (OK)
bower install
pero no encuentra el comando... -bash: bower: command not found

Luego corrí el último comando (por probar) pero tira error igual: 
npm run build_osx64
sh: nwbuild: command not found

Se te ocurre qué me falta? Quizás algo del nw-builder? reiniciar o algo así para que encuentre estos comandos?

No uso mucho Processing, pero la verdad que el IDE es horrible y estaría genial probar esto que hiciste!
Gracias,

**Comment by moebiussurfing** [comment]
![captura de pantalla 2015-09-14 a las 14 55 22](https://cloud.githubusercontent.com/assets/2106149/9862614/4e7a2376-5b10-11e5-8ec5-13896bd0bbd8.png)

![captura de pantalla 2015-09-14 a las 18 42 56](https://cloud.githubusercontent.com/assets/2106149/9862681/c3eae398-5b10-11e5-99d8-3b49e62f1427.png)

**Comment by necsoft** [comment]
No hay problema! Yo tampoco lo dejé muy en claro, después voy a intentar hacer unos pasos mas descriptivos.

Por lo que estoy viendo el problema es que el comando nwbuild solamente aparece cuando instalas el paquete nw-build de manera global con `npm install nw-builder -g` , cuando haces esto lo estas agregando globalmente a node, es similar a otros paquetes que actúan desde la terminal con forma de comando. Proba eso, instalarlo globalmente y luego de terminar escribir "nwbuild" para ver si te tira el "command not found" o la descripción de uso de nwbuild. Cualquier cosa avisame!

**Comment by moebiussurfing** [comment]
Buenas, me sigue sin funcionar... Instalé vía global y anda pero sigue sin encontrar bower, pero me tira este warning respecto a lo de la versión que decías: 
sudo npm install nw-builder -g
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})

Te paso screens de este y otro warning:

![1](https://cloud.githubusercontent.com/assets/2106149/9885525/f9cc48c0-5bbb-11e5-8c26-a6d9a66076d5.png)

![2](https://cloud.githubusercontent.com/assets/2106149/9885526/f9d9f286-5bbb-11e5-9c6c-42b3cd8e3ef8.png)

**Comment by moebiussurfing** [comment]
ahora aunque dé el error de bower, "sudo npm run build_osx64" parece que funca.
Cuando lo pruebe te comento! Gracias y espero que puedas seguir desarrollando esto!

sudo bower install
sudo: bower: command not found
xx:codepoems x$ sudo npm run build_osx64
Password:

> codepoems@0.0.1 build_osx64 /Users/x/Documents/code/codepoems
> rm -rf build/osx64/ && nwbuild --version 0.12.2 --macIcns ./icon/codepoems.icns --platforms osx64 -o ./build/ ./

Using v0.12.2
Create cache folder in /usr/local/lib/node_modules/nw-builder/cache/0.12.2
Downloading: http://dl.nwjs.io/v0.12.2/nwjs-v0.12.2-osx-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /Users/x/Documents/code/codepoems/build/codepoems/osx64

**Comment by moebiussurfing** [comment]
hmm no puedo abrir la app que generó, me sale el icono "como deshabilitado". Tengo activado en seguirdad poder abrir cualquier app de cualquier developer y tampoco funciona lo pulsar control antes de abrir la app...

![captura de pantalla 2015-09-15 a las 15 26 02](https://cloud.githubusercontent.com/assets/2106149/9886059/c97bdf48-5bbe-11e5-8584-7480cc1c7922.png)

Por otro lado, (si bien no estoy 100% seguro que sea de la última prueba) estoy viendo que hay un archivo de log npm-debug.log con esto:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose config Skipping project config: /Users/x/.npmrc. (matches userconfig)
5 verbose readDependencies loading dependencies from /Users/manu/package.json
6 error install Couldn't read dependencies
7 verbose stack Error: ENOENT: no such file or directory, open '/Users/x/package.json'
7 verbose stack     at Error (native)
8 verbose cwd /Users/x/Documents/code
9 error Darwin 14.5.0
10 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
11 error node v4.0.0
12 error npm  v2.14.2
13 error path /Users/x/package.json
14 error code ENOPACKAGEJSON
15 error errno -2
16 error syscall open
17 error package.json ENOENT: no such file or directory, open '/Users/manu/package.json'
17 error package.json This is most likely not a problem with npm itself.
17 error package.json npm can't find a package.json file in your current directory.
18 verbose exit [ -2, true ]

**Comment by necsoft** [comment]
Acabo de hacerme una carpeta aparte para probar por separado y esta secuencia me resultó exitosa, claro que también tengo instaldo bower como paquete global de node:

```
git clone https://github.com/necsoft/codepoems
cd codepoems
bower install
npm install
npm run build_osx64
```

Estoy pensando como puedo hacer para facilitar este proceso aunque esto solo hay que hacerlo cuando se quiere modificar el código y compilar una versión nueva, de hecho también tengo que aclarar como hago para programar en tiempo real desde sublime llamando directamente a nwjs desde sublime.

Puedes probar crear una carpeta aparte y seguir la secuencia que te pasé desde cero, ahora que ya tienes las dos dependencias globales funcionando, sino otra cosa que se me ocurre es que te pase la app compilada, pero definitivamente esto tiene que funcionar. Cuando encontremos los pasos que te resultaron correctos actualizo el README.

Con respecto al desarrollo, estoy intentando terminar la versión de Mac OS X para estas semanas, pero estoy de viaje en Barcelona y mi computadora no para de fallar, asi que lo hago en los ratos que tengo jaja. Gracias por la buena onda!

**Comment by moebiussurfing** [comment]
Hola disfruta del viaje y no te hagas drama! Si me mandas el ejecutable
para probar así no más genial. Si no tampoco pasa nada, cuando retome en
algún momento con algo en Processing lo volveré a intentar. Saludos!

**Comment by necsoft** [comment]
Amigo! Ahi subí los releases, espero que te anden!

**Comment by moebiussurfing** [comment]
jeje gracias, ya lo bajé.
lo vi en el grupo de processing BA
gracias
