### ISSUE TITLE
Program does not open even with processing-java installed

### ISSUE THREAD

**Issue by StuartFarmer** [necsoft/codepoems#86]
Using Processing 3 beta, Mac 10.10.5. Had processing-java installed from prior fiddling, but still get the "You need processing-java installed" modal appearing, preventing use of the IDE.

**Comment by serebit** [comment]
Can confirm. Processing 3 beta, OS X 10.10.5. Have processing-java installed for current user. Dialog box still comes up.

**Comment by necsoft** [comment]
Sorry guys my computer was broken and I'm travelling. I'll add a button like "continue anyways" for these alpha releases. Sorry for the delay!

**Comment by necsoft** [comment]
Moved to #84 !
